include(joinpath("walk", "all.jl"))
include(joinpath("rotate", "all.jl"))
include(joinpath("grid", "all.jl"))
include(joinpath("move", "all.jl"))
include(joinpath("sphere", "all.jl"))
include(joinpath("cylinder", "all.jl"))
